const BiologicalClassification = [
  // Early Classification Systems
  { id: 1, question: "Who was the earliest to attempt a more scientific basis for classification?", answer: "Aristotle." },
  { id: 2, question: "What criteria did Aristotle use to classify plants?", answer: "He used simple morphological characters to classify them into trees, shrubs, and herbs." },
  { id: 3, question: "How did Aristotle classify animals?", answer: "Into two groups: those which had red blood and those that did not." },
  { id: 4, question: "Who developed the Two Kingdom system of classification?", answer: "Linnaeus." },
  { id: 5, question: "What were the two kingdoms in Linnaeus's classification system?", answer: "Plantae and Animalia." },
  { id: 6, question: "What were the major drawbacks of the Two Kingdom classification system?", answer: "It did not distinguish between eukaryotes and prokaryotes, unicellular and multicellular organisms, or photosynthetic (green algae) and non-photosynthetic (fungi) organisms." },

  // Whittaker's Five Kingdom System
  { id: 7, question: "Who proposed the Five Kingdom Classification and in what year?", answer: "R.H. Whittaker in 1969." },
  { id: 8, question: "What are the names of the five kingdoms proposed by Whittaker?", answer: "Monera, Protista, Fungi, Plantae, and Animalia." },
  { id: 9, question: "What were the main criteria used by Whittaker for his classification?", answer: "Cell structure, body organisation, mode of nutrition, reproduction, and phylogenetic relationships." },
  { id: 10, question: "What does the three-domain system of classification entail?", answer: "It divides Kingdom Monera into two domains and leaves the remaining eukaryotic kingdoms in the third domain, creating a six kingdom classification." },
  { id: 11, question: "Why were fungi separated from plants in Whittaker's system?", answer: "Because fungi are heterotrophic and have chitin in their cell walls, whereas green plants are autotrophic and have cellulosic cell walls." },
  { id: 12, question: "Which kingdom contains all prokaryotic organisms according to Whittaker?", answer: "Kingdom Monera." },
  { id: 13, question: "Which kingdom brings together Chlamydomonas and Amoeba?", answer: "Kingdom Protista (uniting all unicellular eukaryotic organisms)." },

  // Kingdom Characteristics (Table 2.1)
  { id: 14, question: "Which is the only kingdom with a prokaryotic cell type?", answer: "Monera." },
  { id: 15, question: "What is the cell wall of Monera composed of?", answer: "Noncellulosic material (Polysaccharide + amino acid)." },
  { id: 16, question: "Which kingdoms possess a nuclear membrane?", answer: "Protista, Fungi, Plantae, and Animalia (all eukaryotic kingdoms)." },
  { id: 17, question: "Which kingdom entirely lacks a cell wall?", answer: "Animalia." },
  
  // Kingdom Monera
  { id: 18, question: "Which organisms are the sole members of Kingdom Monera?", answer: "Bacteria." },
  { id: 19, question: "What are the four shape-based categories of bacteria?", answer: "Spherical Coccus, rod-shaped Bacillus, comma-shaped Vibrium, and spiral Spirillum." },
  { id: 20, question: "Which kingdom shows the most extensive metabolic diversity?", answer: "Kingdom Monera (bacteria)." },
  { id: 21, question: "What are the three types of harsh habitats Archaebacteria live in?", answer: "Extreme salty areas (halophiles), hot springs (thermoacidophiles), and marshy areas (methanogens)." },
  { id: 22, question: "Why can Archaebacteria survive in extreme conditions?", answer: "Due to their different cell wall structure compared to other bacteria." },
  { id: 23, question: "Which bacteria are responsible for the production of biogas (methane) from the dung of ruminants?", answer: "Methanogens." },
  { id: 24, question: "What characterises Eubacteria ('true bacteria')?", answer: "The presence of a rigid cell wall, and if motile, a flagellum." },
  { id: 25, question: "What is another name for cyanobacteria?", answer: "Blue-green algae." },
  { id: 26, question: "What specialised cells allow some cyanobacteria (like Nostoc and Anabaena) to fix atmospheric nitrogen?", answer: "Heterocysts." },
  { id: 27, question: "Which type of bacteria oxidise inorganic substances (nitrates, nitrites, ammonia) for ATP production?", answer: "Chemosynthetic autotrophic bacteria." },
  { id: 28, question: "What role do chemosynthetic autotrophic bacteria play in nature?", answer: "They play a great role in recycling nutrients like nitrogen, phosphorous, iron, and sulphur." },
  { id: 29, question: "Which type of bacteria are most abundant in nature and act as important decomposers?", answer: "Heterotrophic bacteria." },
  { id: 30, question: "Name four well-known diseases caused by heterotrophic bacteria.", answer: "Cholera, typhoid, tetanus, and citrus canker." },
  { id: 31, question: "How do bacteria primarily reproduce?", answer: "Mainly by fission." },
  { id: 32, question: "What are the smallest living cells known that completely lack a cell wall and can survive without oxygen?", answer: "Mycoplasma." },

  // Kingdom Protista
  { id: 33, question: "What organisms are placed under Kingdom Protista?", answer: "All single-celled eukaryotes." },
  { id: 34, question: "What are the five main groups included under Protista?", answer: "Chrysophytes, Dinoflagellates, Euglenoids, Slime moulds, and Protozoans." },
  { id: 35, question: "Which Protista group includes diatoms and golden algae (desmids)?", answer: "Chrysophytes." },
  { id: 36, question: "What unique structure do diatom cell walls have?", answer: "They form two thin overlapping shells that fit together like a soap box, embedded with indestructible silica." },
  { id: 37, question: "What is 'diatomaceous earth' used for?", answer: "Polishing and filtration of oils and syrups." },
  { id: 38, question: "Who are the chief 'producers' in the oceans?", answer: "Diatoms." },
  { id: 39, question: "Which group of protists has stiff cellulose plates on the outer surface of their cell wall?", answer: "Dinoflagellates." },
  { id: 40, question: "Which specific red dinoflagellate undergoes rapid multiplication to cause 'red tides'?", answer: "Gonyaulax." },
  { id: 41, question: "Instead of a cell wall, what protein-rich layer makes the body of euglenoids flexible?", answer: "Pellicle." },
  { id: 42, question: "How do Euglenoids behave when deprived of sunlight?", answer: "They behave like heterotrophs by predating on other smaller organisms." },
  { id: 43, question: "Which protists are saprophytic, move along decaying twigs, and form an aggregation called a plasmodium?", answer: "Slime moulds." },
  { id: 44, question: "What do slime moulds form during unfavourable conditions to survive?", answer: "Fruiting bodies bearing spores with true walls at their tips." },
  { id: 45, question: "What are the four major groups of protozoans?", answer: "Amoeboid, Flagellated, Ciliated, and Sporozoan protozoans." },
  { id: 46, question: "Which amoeboid protozoan acts as a parasite?", answer: "Entamoeba." },
  { id: 47, question: "Which flagellated protozoan causes sleeping sickness?", answer: "Trypanosoma." },
  { id: 48, question: "Which ciliated protozoan has a gullet that steers water laden with food into it?", answer: "Paramoecium." },
  { id: 49, question: "Which notorious sporozoan causes malaria?", answer: "Plasmodium." },

  // Kingdom Fungi
  { id: 50, question: "Which common unicellular fungus is an exception to the normally filamentous nature of fungi?", answer: "Yeast." },
  { id: 51, question: "What is a network of long, slender, thread-like fungal hyphae called?", answer: "Mycelium." },
  { id: 52, question: "What are continuous tube-like hyphae filled with multinucleated cytoplasm called?", answer: "Coenocytic hyphae." },
  { id: 53, question: "What two materials compose the cell walls of fungi?", answer: "Chitin and polysaccharides." },
  { id: 54, question: "What are the two symbiotic associations of fungi mentioned in the text?", answer: "Lichens (with algae) and mycorrhiza (with roots of higher plants)." },
  { id: 55, question: "What are the three asexual spores of fungi?", answer: "Conidia, sporangiospores, and zoospores." },
  { id: 56, question: "What are the three sexual spores of fungi?", answer: "Oospores, ascospores, and basidiospores." },
  { id: 57, question: "What are the three steps in the fungal sexual cycle?", answer: "1. Plasmogamy 2. Karyogamy 3. Meiosis in zygote." },
  { id: 58, question: "What is the intervening stage in ascomycetes and basidiomycetes where cells have two nuclei (n + n)?", answer: "Dikaryon (the phase is called dikaryophase)." },
  { id: 59, question: "Which class of fungi has aseptate and coenocytic mycelium?", answer: "Phycomycetes." },
  { id: 60, question: "Give three examples of Phycomycetes.", answer: "Mucor, Rhizopus (bread mould), and Albugo (mustard parasite)." },
  { id: 61, question: "What are Ascomycetes commonly known as?", answer: "Sac-fungi." },
  { id: 62, question: "How are asexual conidia and sexual ascospores produced in Ascomycetes?", answer: "Conidia are produced exogenously, and ascospores are produced endogenously in asci." },
  { id: 63, question: "Give three examples of Ascomycetes.", answer: "Aspergillus, Claviceps, and Neurospora." },
  { id: 64, question: "Which ascomycete is used extensively in biochemical and genetic work?", answer: "Neurospora." },
  { id: 65, question: "What are the commonly known forms of Basidiomycetes?", answer: "Mushrooms, bracket fungi, or puffballs." },
  { id: 66, question: "How is plasmogamy brought about in Basidiomycetes since sex organs are absent?", answer: "By fusion of two vegetative or somatic cells of different strains or genotypes." },
  { id: 67, question: "Give three examples of Basidiomycetes.", answer: "Agaricus (mushroom), Ustilago (smut), and Puccinia (rust fungus)." },
  { id: 68, question: "Why are Deuteromycetes known as 'imperfect fungi'?", answer: "Because only the asexual or vegetative phases of these fungi are known." },
  { id: 69, question: "Give three examples of Deuteromycetes.", answer: "Alternaria, Colletotrichum, and Trichoderma." },

  // Kingdom Plantae & Animalia
  { id: 70, question: "Give two examples of insectivorous plants (partially heterotrophic Plantae).", answer: "Bladderwort and Venus fly trap." },
  { id: 71, question: "Give an example of a parasitic plant.", answer: "Cuscuta." },
  { id: 72, question: "What is the phenomenon in plants where diploid sporophytic and haploid gametophytic phases alternate?", answer: "Alternation of generation." },
  { id: 73, question: "How do members of Kingdom Animalia store their food reserves?", answer: "As glycogen or fat." },
  { id: 74, question: "What is the mode of nutrition in Kingdom Animalia?", answer: "Holozoic (by ingestion of food)." },

  // Viruses, Viroids, Prions and Lichens
  { id: 75, question: "Why did viruses not find a place in Whittaker's classification?", answer: "Because they are not considered truly 'living' as they do not have a cell structure." },
  { id: 76, question: "Who recognised certain microbes as the causal organism of tobacco mosaic disease in 1892?", answer: "Dmitri Ivanowsky." },
  { id: 77, question: "Who named the new pathogen 'virus' and called the fluid Contagium vivum fluidum in 1898?", answer: "M.W. Beijerinek." },
  { id: 78, question: "Who showed in 1935 that viruses could be crystallised and consist largely of proteins?", answer: "W.M. Stanley." },
  { id: 79, question: "Can a virus contain both RNA and DNA?", answer: "No, no virus contains both RNA and DNA." },
  { id: 80, question: "What type of genetic material do plant-infecting viruses generally have?", answer: "Single stranded RNA." },
  { id: 81, question: "What type of genetic material do bacteriophages (bacterial viruses) usually have?", answer: "Double stranded DNA." },
  { id: 82, question: "What is the protein coat of a virus called, and what are its small subunits?", answer: "The coat is called a capsid, made of subunits called capsomeres." },
  { id: 83, question: "Name four human diseases caused by viruses (excluding AIDS).", answer: "Mumps, small pox, herpes, and influenza." },
  { id: 84, question: "Who discovered viroids in 1971?", answer: "T.O. Diener." },
  { id: 85, question: "How do viroids differ structurally from viruses?", answer: "They are free RNA of low molecular weight and lack the protein coat found in viruses." },
  { id: 86, question: "What disease is caused by viroids?", answer: "Potato spindle tuber disease." },
  { id: 87, question: "What are infectious agents consisting of abnormally folded proteins called?", answer: "Prions." },
  { id: 88, question: "What notable disease do prions cause in cattle?", answer: "Bovine spongiform encephalopathy (BSE) or 'mad cow disease'." },
  { id: 89, question: "What is the human analogue of mad cow disease caused by prions?", answer: "Cr-Jacob disease (CJD)." },
  { id: 90, question: "What are the two mutually useful components of lichens?", answer: "The algal component (phycobiont) and the fungal component (mycobiont)." },
  { id: 91, question: "Why are lichens considered very good pollution indicators?", answer: "Because they do not grow in polluted areas." },

  // Conceptual Additions
  { id: 92, question: "Why was the Two Kingdom classification system found inadequate?", answer: "Because it could not distinguish prokaryotes from eukaryotes, unicellular from multicellular organisms, and fungi from plants." },
  { id: 93, question: "What is the basis of modern classification systems?", answer: "Evolutionary relationships along with morphological, cytological and genetic characteristics." },
  { id: 94, question: "Why is Kingdom Protista considered a link between plants, animals and fungi?", answer: "Because it contains organisms showing characteristics similar to all three groups." },
  { id: 95, question: "What is the importance of cyanobacteria in nature?", answer: "They act as photosynthetic producers and many can fix atmospheric nitrogen." },
  { id: 96, question: "Name two cyanobacteria capable of nitrogen fixation.", answer: "Nostoc and Anabaena." },
  { id: 97, question: "Why are methanogens economically important?", answer: "They produce methane gas and are used in biogas production." },
  { id: 98, question: "Why are diatoms called chief producers of oceans?", answer: "Because they perform a large share of marine photosynthesis." },
  { id: 99, question: "Why are diatom walls preserved for billions of years?", answer: "Because their walls contain indestructible silica." },
  { id: 100, question: "What is the ecological significance of red tides?", answer: "They may release toxins that kill marine animals such as fish." },
  { id: 101, question: "Why are Euglenoids considered both plant-like and animal-like?", answer: "They photosynthesize in sunlight but become heterotrophic in the absence of light." },
  { id: 102, question: "What is plasmodium in slime moulds?", answer: "A multinucleate mass of protoplasm formed by aggregation of cells." },
  { id: 103, question: "Why can slime mould spores survive adverse conditions?", answer: "Because they possess resistant true walls." },
  { id: 104, question: "What is the nutritional mode of most fungi?", answer: "Absorptive heterotrophic nutrition." },
  { id: 105, question: "Why are fungi important decomposers?", answer: "They break down dead organic matter and recycle nutrients." },
  { id: 106, question: "What are morels and truffles?", answer: "Edible members of Ascomycetes considered delicacies." },
  { id: 107, question: "What is the economic importance of yeast?", answer: "It is used in baking and fermentation industries." },
  { id: 108, question: "What is the significance of Neurospora?", answer: "It is widely used in genetic and biochemical studies." },
  { id: 109, question: "What is the significance of lichens?", answer: "They indicate air pollution levels and represent symbiosis between algae and fungi." },
  { id: 110, question: "Which partner provides food in lichens?", answer: "The algal partner." },
  { id: 111, question: "Which partner provides shelter and water in lichens?", answer: "The fungal partner." },
  { id: 112, question: "Why are insectivorous plants considered partially heterotrophic?", answer: "Because they photosynthesize but obtain nitrogen by trapping insects." },
  { id: 113, question: "Why is Cuscuta considered a parasitic plant?", answer: "Because it derives nutrition from a host plant." },
  { id: 114, question: "Why are viruses considered living only inside host cells?", answer: "Because they can reproduce only within living cells." },
  { id: 115, question: "Why are viruses considered non-living outside host cells?", answer: "Because they remain inert and can even be crystallized." },
  { id: 116, question: "What is the significance of W.M. Stanley's work?", answer: "He demonstrated that viruses can be crystallized." },
  { id: 117, question: "Why are viroids simpler than viruses?", answer: "Because they consist only of RNA and lack a protein coat." },
  { id: 118, question: "What are prions made of?", answer: "Abnormally folded infectious proteins." },
  { id: 119, question: "Why are prions unique infectious agents?", answer: "Because they contain protein only and no nucleic acid." },
  { id: 120, question: "Which kingdom shows the greatest metabolic diversity?", answer: "Monera." },
  { id: 121, question: "Which kingdom contains both autotrophic and heterotrophic unicellular eukaryotes?", answer: "Protista." },
  { id: 122, question: "What is mycorrhiza?", answer: "A symbiotic association between fungi and roots of higher plants." },

{ id: 123, question: "What benefit do fungi obtain in mycorrhiza?", answer: "They obtain food from the plant roots." },

{ id: 124, question: "What benefit does the plant receive in mycorrhiza?", answer: "Enhanced absorption of water and minerals." }
];

export default BiologicalClassification;