const LivingWorld = [
  // Introduction & Ernst Mayr
  { id: 1, question: "What is biology?", answer: "The science of life forms and living processes." },
  { id: 2, question: "Who has been called 'The Darwin of the 20th century'?", answer: "Ernst Mayr." },
  { id: 3, question: "Where and when was Ernst Mayr born?", answer: "Kempten, Germany on 5 July 1904." },
  { id: 4, question: "What title did Ernst Mayr assume upon retiring from Harvard in 1975?", answer: "Alexander Agassiz Professor of Zoology Emeritus." },
  { id: 5, question: "What three prizes constitute the 'triple crown of biology' awarded to Ernst Mayr?", answer: "The Balzan Prize (1983), the International Prize for Biology (1994), and the Crafoord Prize (1999)." },

  // What is 'Living'?
  { id: 6, question: "What are the twin characteristics of growth?", answer: "Increase in mass and increase in number of individuals." },
  { id: 7, question: "How does growth duration differ between plants and animals?", answer: "Plants grow continuously throughout their lifespan, while animals grow only up to a certain age." },
  { id: 8, question: "Why is growth not considered a defining property of living organisms?", answer: "Because non-living objects (like mountains and sand mounds) also grow by accumulating material on the surface." },
  { id: 9, question: "What is the defining difference between the growth of living and non-living things?", answer: "Living organisms grow from the inside, while non-living things grow by accumulation from the outside." },
  { id: 10, question: "Name an organism that reproduces through true regeneration.", answer: "Planaria (flat worms)." },
  { id: 11, question: "How do fungi multiply and spread easily?", answer: "By producing millions of asexual spores." },
  { id: 12, question: "Name three organisms that easily multiply by fragmentation.", answer: "Fungi, filamentous algae, and the protonema of mosses." },
  { id: 13, question: "In which organisms is reproduction synonymous with growth?", answer: "Unicellular organisms like bacteria, unicellular algae, and Amoeba." },
  { id: 14, question: "Name three examples of living organisms that do not reproduce.", answer: "Mules, sterile worker bees, and infertile human couples." },
  { id: 15, question: "What is metabolism?", answer: "The sum total of all the chemical reactions occurring in the body." },
  { id: 16, question: "Are isolated metabolic reactions in vitro considered living things?", answer: "No, they are not living things, but they are living reactions." },
  { id: 17, question: "What is the defining feature of life forms?", answer: "Cellular organisation of the body." },
  { id: 18, question: "What is the most obvious and technically complicated feature of all living organisms?", answer: "The ability to sense their environment and respond to environmental stimuli." },
  { id: 19, question: "What environmental factor affects reproduction in seasonal breeders?", answer: "Photoperiod." },
  { id: 20, question: "Which is the only organism that is aware of himself (has self-consciousness)?", answer: "Human beings." },
  { id: 21, question: "What is the ultimate defining property of all living organisms?", answer: "Consciousness." },
  { id: 22, question: "Where do the properties of tissues come from?", answer: "They are not present in constituent cells but arise as a result of interactions among the constituent cells." },
  { id: 23, question: "Define living organisms based on their systemic properties.", answer: "They are self-replicating, evolving, and self-regulating interactive systems capable of responding to external stimuli." },

  // Diversity in the Living World
  { id: 24, question: "What is biodiversity?", answer: "The number and types of organisms present on earth." },
  { id: 25, question: "How many species are currently known and described?", answer: "Between 1.7 to 1.8 million." },
  { id: 26, question: "What does ICBN stand for?", answer: "International Code for Botanical Nomenclature." },
  { id: 27, question: "What does ICZN stand for?", answer: "International Code of Zoological Nomenclature." },
  { id: 28, question: "What are the two components of a biological name?", answer: "The generic name and the specific epithet." },
  { id: 29, question: "Who introduced the system of Binomial nomenclature?", answer: "Carolus Linnaeus." },
  { id: 30, question: "What is the scientific name of mango?", answer: "Mangifera indica." },
  { id: 31, question: "In biological nomenclature, what language are names generally derived from?", answer: "Latin." },
  { id: 32, question: "How should a biological name be formatted when handwritten?", answer: "Both words must be separately underlined." },
  { id: 33, question: "What does the abbreviation 'Linn.' at the end of 'Mangifera indica Linn.' signify?", answer: "It indicates that the species was first described by Linnaeus." },
  { id: 34, question: "What is the scientific term for the categories used in classification?", answer: "Taxa." },
  { id: 35, question: "What process involves characterizing, identifying, classifying, and naming organisms?", answer: "Taxonomy." },
  { id: 36, question: "From which Latin word is 'systematics' derived, and what does it mean?", answer: "Derived from 'systema', meaning systematic arrangement of organisms." },
  { id: 37, question: "What was the title of Carolus Linnaeus's publication?", answer: "Systema Naturae." },
  { id: 38, question: "What key aspect does systematics take into account that taxonomy does not inherently?", answer: "Evolutionary relationships between organisms." },

  // Taxonomic Categories
  { id: 39, question: "What is the lowest category in the taxonomic hierarchy?", answer: "Species." },
  { id: 40, question: "What is the specific epithet for the potato plant?", answer: "tuberosum (Solanum tuberosum)." },
  { id: 41, question: "Name two other species that belong to the genus Solanum besides potato.", answer: "Solanum nigrum and Solanum melongena." },
  { id: 42, question: "What is the scientific name for a lion?", answer: "Panthera leo." },
  { id: 43, question: "What specific epithet designates a tiger?", answer: "tigris (Panthera tigris)." },
  { id: 44, question: "What genus includes cats?", answer: "Felis." },
  { id: 45, question: "What two criteria are plant families primarily characterized by?", answer: "Vegetative and reproductive features." },
  { id: 46, question: "Which three genera are placed in the plant family Solanaceae?", answer: "Solanum, Petunia, and Datura." },
  { id: 47, question: "Which two families are included in the animal order Carnivora?", answer: "Felidae (cats, lions, tigers) and Canidae (dogs)." },
  { id: 48, question: "What is the primary basis for including plant families Convolvulaceae and Solanaceae in the order Polymoniales?", answer: "Floral characters." },
  { id: 49, question: "Which animal order comprises monkeys, gorillas, and gibbons?", answer: "Primata." },
  { id: 50, question: "The class Mammalia includes which two mentioned orders?", answer: "Primata and Carnivora." },
  { id: 51, question: "What two common features place fishes, amphibians, reptiles, birds, and mammals in the phylum Chordata?", answer: "Presence of a notochord and a dorsal hollow neural system." },
  { id: 52, question: "In plants, what taxonomic category is equivalent to Phylum in animals?", answer: "Division." },
  { id: 53, question: "As you go higher from species to kingdom, what happens to the number of common characteristics?", answer: "The number of common characteristics goes on decreasing." },

  // Classification Table Breakdown (Table 1.1)
  { id: 54, question: "What is the biological name of man?", answer: "Homo sapiens." },
  { id: 55, question: "What is the Family and Order of humans?", answer: "Family: Hominidae, Order: Primata." },
  { id: 56, question: "What is the biological name of the housefly?", answer: "Musca domestica." },
  { id: 57, question: "What is the Family and Order of the housefly?", answer: "Family: Muscidae, Order: Diptera." },
  { id: 58, question: "What Class and Phylum does the housefly belong to?", answer: "Class: Insecta, Phylum: Arthropoda." },
  { id: 59, question: "What is the Family and Order of mango?", answer: "Family: Anacardiaceae, Order: Sapindales." },
  { id: 60, question: "What Class and Division does mango belong to?", answer: "Class: Dicotyledonae, Division: Angiospermae." },
  { id: 61, question: "What is the biological name of wheat?", answer: "Triticum aestivum." },
  { id: 62, question: "What is the Family and Order of wheat?", answer: "Family: Poaceae, Order: Poales." },
  { id: 63, question: "What Class and Division does wheat belong to?", answer: "Class: Monocotyledonae, Division: Angiospermae." },

  // Taxonomical Aids
  { id: 64, question: "What is a herbarium?", answer: "A store house of collected plant specimens that are dried, pressed, and preserved on sheets." },
  { id: 65, question: "What information does a herbarium sheet label provide?", answer: "Date and place of collection, English, local and botanical names, family, and the collector's name." },
  { id: 66, question: "Which taxonomical aid serves as a quick referral system?", answer: "Herbaria." },
  { id: 67, question: "What is the main purpose of Botanical Gardens?", answer: "They house collections of living plants grown for reference and identification purposes." },
  { id: 68, question: "Where are the three famous botanical gardens mentioned in the text located?", answer: "Kew (England), Howrah (India), and Lucknow (India)." },
  { id: 69, question: "How are insects typically preserved in a biological museum?", answer: "They are collected, killed, and pinned in insect boxes." },
  { id: 70, question: "What is a couplet in a taxonomic key?", answer: "A pair of contrasting characters representing a choice between two opposite options." },
  { id: 71, question: "What is each individual statement in a taxonomic key called?", answer: "A lead." },
  { id: 72, question: "What taxonomical aid provides the actual account of habitat and distribution of plants of a given area?", answer: "Flora." },
  { id: 73, question: "What is the purpose of manuals in taxonomy?", answer: "They provide information for the identification of names of species found in a particular area." },
  { id: 74, question: "What taxonomical aid contains information on only one taxon?", answer: "Monographs." },

  // Conceptual Additions
  { id: 75, question: "Why are living organisms referred to as systems?", answer: "Because they are made of interacting components that work together as a whole." },
  { id: 76, question: "Why is growth in plants considered indeterminate?", answer: "Because plants continue to grow throughout their lifespan." },
  { id: 77, question: "Why is growth in animals considered determinate?", answer: "Because animals stop growing after attaining a certain age." },
  { id: 78, question: "Why is reproduction not an all-inclusive defining characteristic of living organisms?", answer: "Because some living organisms such as mules and worker bees do not reproduce." },
  { id: 79, question: "What are metabolic reactions collectively known as?", answer: "Metabolism." },
  { id: 80, question: "Why is metabolism regarded as a defining feature of life?", answer: "Because all living organisms perform metabolic reactions." },
  { id: 81, question: "What is meant by in vitro metabolism?", answer: "Metabolic reactions performed outside the living body in laboratory conditions." },
  { id: 82, question: "Why are isolated metabolic reactions called living reactions?", answer: "Because they are reactions normally found only in living organisms." },
  { id: 83, question: "What is irritability in living organisms?", answer: "The ability to sense and respond to environmental stimuli." },
  { id: 84, question: "What is consciousness in biological terms?", answer: "Awareness of surroundings and the ability to respond to stimuli." },
  { id: 85, question: "Why is consciousness considered the defining property of living organisms?", answer: "Because all living organisms can sense and respond to their environment." },
  { id: 86, question: "What is the significance of biodiversity?", answer: "It reflects the variety of life forms present on Earth." },
  { id: 87, question: "Why is naming organisms necessary?", answer: "To avoid confusion caused by local names and ensure universal communication." },
  { id: 88, question: "Why are scientific names universal?", answer: "Because they follow internationally accepted rules of nomenclature." },
  { id: 89, question: "What is identification in taxonomy?", answer: "The process of determining the correct name of an organism." },
  { id: 90, question: "What is characterisation in taxonomy?", answer: "The process of describing an organism's distinctive features." },
  { id: 91, question: "What is classification?", answer: "The arrangement of organisms into groups based on similarities and differences." },
  { id: 92, question: "What is nomenclature?", answer: "The process of assigning scientific names to organisms." },
  { id: 93, question: "Why is species considered the basic unit of classification?", answer: "Because it represents a group of closely related organisms capable of interbreeding." },
  { id: 94, question: "What happens to similarities among organisms as we move from species to kingdom?", answer: "Similarities decrease while diversity increases." },
  { id: 95, question: "Why are taxonomic keys important?", answer: "They help identify organisms using contrasting characters." },
  { id: 96, question: "What is the purpose of biological museums?", answer: "To preserve and display specimens for study and identification." },
  { id: 97, question: "How are larger animals preserved in museums?", answer: "They are usually stuffed and preserved, or kept as skeletal collections." },
  { id: 98, question: "What is the role of a flora?", answer: "It provides information about plants of a particular region." },
  { id: 99, question: "What is the role of a monograph?", answer: "It provides detailed information about a single taxon." },
  { id: 100, question: "Why are taxonomical aids important?", answer: "They help in identification, classification and study of organisms." },
  { id: 101, question: "What is nomenclature?", answer: "The process of assigning scientific names to organisms." },
  { id: 102, question: "Why are local names problematic in biology?", answer: "The same organism may have different names in different languages and regions." },
  { id: 103, question: "What is the first step in taxonomy?", answer: "Characterisation of the organism." },
  { id: 104, question: "What is meant by taxonomic hierarchy?", answer: "The arrangement of taxonomic categories in ascending order." },
  { id: 105, question: "Which category is the highest in taxonomic hierarchy?", answer: "Kingdom." },
  { id: 106, question: "Why is species called a natural taxon?", answer: "Because members share common characteristics and can interbreed." },
  { id: 107, question: "What is a taxon?", answer: "A unit of classification at any rank." },
  { id: 108, question: "What is the importance of botanical gardens?", answer: "They help in plant identification, research and conservation." },
  { id: 109, question: "What is the importance of herbaria?", answer: "They provide preserved plant specimens for study and reference." },
  { id: 110, question: "What is the importance of museums in taxonomy?", answer: "They preserve specimens for identification and research." }
];

export default LivingWorld;